const SUPABASE_URL = "https://nfyygpxuqxasusjgyola.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5meXlncHh1cXhhc3Vzamd5b2xhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyMDgwMDEsImV4cCI6MjA4Njc4NDAwMX0.RzePuduvkIuLPfdGfYq6zkEosce_jiFo67_KrYp0aDA";

